spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9090/file:C:/Users/logonrmlocal/fiap-card
    username: fiap
    password: fiap
  batch:
    jdbc:
      initialize-schema: always
      schema: classpath:schema-h2.sql

file:
  resource: lista_alunos2.txt

